NCI-C4CP/connectApp

- js/pages/consent.js
* CID 335767902 was being set on the consentSubmit() function within consent.js AFTER calling storeResponse()
* shifting around a few lines of code to make sure value is set before storing information to backend db
> ensuring 335767902 is set when consent submitted

- js/pages/homePage.js
This PR follows #437 and #438. 
The update changes default error message to "Enter a valid email address" when creating a new account with email.
> Change error message when creating a new email account

- js/pages/homePage.js
This PR follows #437, #438 and #439.
The update makes sure `idToken` is set before calling `checkAccount()`.
> fix error when checking account

- js/pages/homePage.js
This PR update #437, to solve email search error for some accounts (eg: me+apitest@gmailcom).
Special characters (`%`, `#`, `&`, `'`, `+`) are replaced before adding to url.
> replace characters in email for query

- js/pages/samples.js
Added in a new template because these four are in a slightly different order than other locations.
The Preparation instruction area kpnw and kphi has a header of "What should I Bring to the Visit?" while kpco and kpga the header is "How Should I prepare on the Day of My Visit?" -- this is the reason why there is a prepInstructionsHeader key as well as a prepInstructionsText key.
the new json files use the following keys:
{
concept: text;
name: text;
donatingSamples: text;
whenToDonate: text;
howToDonateBloodAndUrine: text;
prepInstructionsHeader: text;
prepInstructionsText: text;
whatHappensDuring: text;
whatHappensAfter: text;
howToDonateSaliva: text;
support: text;
}
> add kpga kphi kpco and kpnw to the sample page

- js/event.js
- js/pages/consent.js
- js/shared.js
This PR fiexes issue [#610](https://github.com/episphere/connect/issues/610). Below are details:
- `formData['335767902'] = new Date().toISOString();` is removed from `consentSubmit()`. This line is the source of the problem. The value of CID 335767902 is set when a user responds to the first page (about the PIN) after logging in, so there's no need to set it again when the consent is submitted.
- Clean up some code.
> Fix incorrect sign-in time

- app.js
This PR addresses issue https://github.com/episphere/connectApp/issues/475
* Adds noop callback functions when declaring script for Google Maps Javascript API
* Cause of issue and resolution found at https://stackoverflow.com/questions/75179573/how-to-fix-loading-the-google-maps-javascript-api-without-a-callback-is-not-supp
> Google Maps API Error

- js/pages/consent.js
- js/shared.js
This PR updates [PR #485](https://github.com/episphere/connectApp/pull/485), to solve issue [#98](https://github.com/episphere/connectApp/issues/98). Below are details:
- Updated mobile device check, based on feedbacks from PR #485. Beside phones, the new tab feature will also apply to tablets and other devices with touchscreens.
- Handle multiple new tabs.
Note: This update needs to be tested on Windows desktop or laptop with touchscreens, to make sure the download links work as expected.
References:
- [Mobile device detection](https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent#mobile_device_detection)
- [Media Features](https://www.w3.org/TR/mediaqueries-4/#mf-interaction)
- [Window.navigator](https://developer.mozilla.org/en-US/docs/Web/API/Window/n …
> New tab in devices with touchscreen

- js/pages/homePage.js
- js/shared.js
This PR is to solve [issue #482](https://github.com/episphere/connectApp/issues/482) during magic link sign-in. Below are details:
- Implemented a new function `elementIsLoaded` to wait for the email confirmation page (after clicking the magic link) to load.
- In the case of slow internet or slow device, this update waits longer time (up to 1.5 seconds) to render auto sign-in (without the extra email confirmation). Beyond the maximum waiting time, the app will fall back to the default UI for email confirmation.
> Update magic link handling

- js/pages/agreements.js
- js/pages/consent.js
- js/shared.js
This PR is to update previous implementation for issue [#98](https://github.com/episphere/connectApp/issues/98), to handle downloading of signed forms in mobile devices. Two new functions(`generateSignedPdf` and `downloadSignedPdf`) were added.
> New tab for signed consent forms in mobile

- js/pages/agreements.js
This PR is to update previous implementation for issue [#98](https://github.com/episphere/connectApp/issues/98). Below are details:
- Handle signed form download in `forms` section of app, using `downloadSignedPdf` function
- Adjusted name, date and signature positions in signed forms because of position shift
- Retired `renderDownloadConsentCopy` and `renderDownloadHIPAA` functions
> Handle consent form download in 'forms' tab

- js/pages/settings.js
- js/settingsHelpers.js
This PR handles user profile archiving in connectApp.
It also fixes a couple of lingering bugs in issue #20 - making user profiles editable in connectApp after verification.
issue 635: https://github.com/episphere/connect/issues/635
issue 20: https://github.com/episphere/connectApp/issues/20
-update & test logic around history writing
-added `refreshUserData()` to update userData after successful write. This gets past the issue where multiple writes in the same screen caused the latest write to overwrite the previous one.
Profile archiving rules:
-create new object {} in user history for each profile update and include timestamp for the user action.
-if field was empty and user adds data, write an empty string to history.
-if field was populated and user removes data, write an empty …
> #635 - connectApp segment - user profile archiving

- js/pages/homePage.js
Here's a quick PR addressing [issue 570](https://github.com/episphere/connectApp/issues/570)
It adds a description of who to contact when a participant can't remember login information:
“If you’re having trouble signing in or don’t remember your account information, please contact the Connect Support Center at 1-866-462-6621 or ConnectStudy@norc.org before creating a new account.”
> update login not found explanation text

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
This PR addresses issue https://github.com/episphere/connectApp/issues/558 -  Implement the content below as the description for the new COVID-19 Survey on the PWA dashboard in dev `This survey asks questions about your history of COVID-19, including any vaccinations you may have received and details about times you may have gotten sick with COVID-19.`
- Added `ModuleCovid19` concept ids in `fieldToConceptIdMapping.js`
- Added `questionnaireModule` for covid-19 in `shared.js`
- Added informations for module covid-19 in `myToDoList.js`
> [#558] Content for COVID-19 Survey description

- js/fieldToConceptIdMapping.js
- js/pages/settings.js
- js/settingsHelpers.js
This PR is in continued support of https://github.com/episphere/connect/issues/635
It addresses BigQuery compatibility requests from the data team:
(1) disconnect previously empty phone permissions from profile history (don’t tie them to the phone number)
(2) force datatypes
√-suffix: wrap with parseInt
√-suffix: if populated then deleted, use new cId 398561594
√-phone permissions: wrap with parseInt
(3) write on data deletion
√-phone numbers empty string (unchanged)
√-phone permissions: default to 104430631 ('no') instead of empty string
(4) write to history
√-suffix: if previously undefined, use new cId 398561594
√-phone permissions
√-if existing phoneNumber value is falsy, do not write permissions to history
(5) UI: handle undefined suffix related to new cId 398561594
(6) UI: Fix …
> profile version -> data team compatibility request

- app.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/consent.js
- js/pages/settings.js
- js/settingsHelpers.js
This PR is in support of
Connect issue 564 https://github.com/episphere/connect/issues/654
and (separate item, specifying since the number is the same)
ConnectApp PR 564 https://github.com/episphere/connectApp/pull/564
and
Issue: https://github.com/episphere/connect/issues/666
Re: expand name search
•Write updates to `query.firstName` and `query.lastName` fields as arrays.
query.firstName field includes: consent first name (471168198), first name (399159511), and preferred name (153211406).
query.lastName field includes: consent last name (736251808) and last name(996038075).
•Write query.firstName and query.lastName as array on signup (compatible with new data structure and connectFaas search function).
Re: Multi-logins
•Fix handling of `phone`, `password`, and `passwordAndPhone` sign-in …
> Connect app expand name search & fix multi-login type reporting

- js/pages/questionnaire.js
* https://github.com/episphere/connect/issues/672
-----
* Start date of current menstrual cycle wasn't being passed in from clinical biospecimen survey results
-----
* Added Clinical Biospecimen Survey to array of surveys we try to grab data from before starting a survey
* If Clinical Biospecimen Survey data exists AND CID `644459734` (Menstrual Start Date) is present, add it to Quest Input Data
> Adding Clinical Survey Data to Quest Pipeline

- js/event.js
This PR addresses issue https://github.com/episphere/connect/issues/678
-write prefName to query.name array on signup if participant includes a preferred name. Omit if it's a duplicate of first name.
> include prefName in signup search

- js/pages/questionnaire.js
* https://github.com/episphere/connect/issues/702
-----
* PWA was allowing buttons to be clicked when a module was started prior to Quest fully rendering the module. This caused the page to unexpected crash and reload while adding a `?` to the page URL, causing our code to think we were passing in parameters.
-----
* Added code to modify visibility parameter of Quest div
* Changed syntax of passing a function to `then()`
> Quest Rendering Bug Fix

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
* https://github.com/episphere/connect/issues/717
-----
* The Menstrual Cycle Survey shouldn't be showing up on the list of available surveys for a participant if they completed their Biospecimen Survey more than 45 days ago
-----
* Added constant in `fieldToConceptIdMapping.js`
* Added add logic for determining if Menstrual Cycle Survey should be displayed
NOTE: The survey will always be displayed if they have submitted the survey
> Menstrual Cycle Survey - 45 day expiration

- js/shared.js
* https://github.com/episphere/connect/issues/702
-----
* If a question mark is added to the end of our URL the code thinks we have parameters and tries to read them appropriately, but the code throws an error if no parameters are passed.
-----
* set variable `split` to avoid multiple calls to split() function
* checking if `value` is truthy before trying to act on it
> GetParameters() Bug Fix

- js/components/navbar.js
* https://github.com/episphere/connect/issues/700
-----
* Error is caught if the `My Samples` page is put in the page URL prior to participant "having access" to the page
* The error is caught, but the page is rendered regardless, so logic is reflecting the idea that we should just basically mute the bug
-----
* changed logic to have div id `connectSamples` always render
* added dynamic attribute to add `hidden` tag if needed
> Null Property 'click' Bug Fix

- js/fieldToConceptIdMapping.js
This PR change mouthwash kit type concept ID to 976461859, as part of implementations needed for issue [#737](https://github.com/episphere/connect/issues/737).
> Concept ID updage

- js/pages/questionnaire.js
This PR is a second pass at the following PR:
* https://github.com/episphere/connectApp/pull/673
* https://github.com/episphere/connect/issues/837
-----
* If a new Release was created in the Quest repo, changes were automatically seen across all branches of the PWA. We want to import Quest functionality from different sources depending on the URL being used in the PWA
-----
* Removed top-level imports of needed Quest functions
* Created function importQuest that imports Quest library from a URL based on `location.host`
* Added references to global variable `quest`
NOTE: A new file was created to manage the logic of this PR (https://github.com/episphere/questionnaire/blob/main/questVersions.js)
> Enabling Dynamic Quest Versions

- js/pages/questionnaire.js
This update relied on a newer version of Quest that was going to go live at the same time. During testing of that new version, errors were found that regressed grid functionality and the decision was made to not go live. If that version doesn't go live, this code will break production.
Issue: https://github.com/episphere/connect/issues/837
> Revert "Enabling Dynamic Quest Versions"

- js/pages/questionnaire.js
This PR addresses a bug from the following Pull Request:
* https://github.com/episphere/connectApp/pull/695
-----
* Event Listeners are created when modules are booted up and null checks need to be put in place for when someone starts Module 1 for the first time.
-----
* Added null checks to four variable declarations in `questionnaire.js`
> PR 695 - Bug Fix

- js/pages/questionnaire.js
This PR addresses an edge case from the following Pull Request:
* https://github.com/episphere/connectApp/pull/695
-----
* For participants that started Module 1 prior to the January 2024 Release, the Module 1 markdown will not contain questions `WORK3B` or `WORK7B`. In this scenario the event listener that is intended to trigger Soccer would never get created and Soccer would never be called. Code changes are needed to make sure that Soccer can still be called as it was before via `WORK3` and `WORK7` while also allowing it to be called how we want to in the future via `WORK3B` and `WORK7B`.
-----
* Adding event listeners as necessary depending on which questions exist in the version of Module 1 the participant is taking.
> PR 695 - Edge Case

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
* https://github.com/episphere/connect/issues/877
-----
* New PROMIS QOL Survey is being added to the study and logic needs to be put in to display the survey at the right time on the To-Do List, render the appropriate Quest markdown, and send off survey responses to the API
-----
* Added PROMIS survey Concept IDs and new module status Concept ID to `fieldToConceptIdMapping.js`
* Added PROMIS survey information in `myToDoList.js`
* Added logic to push PROMIS survey to the Display System in `myToDoList.js`
* Added logic to mark PROMIS survey as enabled and completed in `myToDoList.js`
* Added PROMIS dev / stage and prod configurations to `questionnaireModules()` in `shared.js`
* Unrelated eslint clean-up to `resetMenstrualCycleSurvey()` in `shared.js`
> PROMIS Survey Updates (PWA)

- js/pages/consent.js
Details of this PR:
- For historical reasons, HP forms have been used for NCI test accounts. This PR allows NCI test accounts use NCI forms. It follows changes in PR [#711](https://github.com/episphere/connectApp/pull/711).
- A minor fix and cleanup
> NCI forms for NCI test accounts

- js/pages/questionnaire.js
Update Quest age calculation to handle the Firestore / JS Date() indexing discrepancy. Firestore month is 1-indexed, JS Date() month is 0-indexed.
• Align date representations and calculate age in years
> 916 update Quest age calculation

- js/fieldToConceptIdMapping.js
This PR addresses the following:
- https://github.com/episphere/connect/issues/901
- https://github.com/episphere/connect/issues/901#issuecomment-1979385034
**Problem: 10 digit concept Id was being used for BioKit_Mouthwash**
Update BioKit_Mouthwash concept Id from `8583443674` to `319972665`
> Update BioKit_Mouthwash Assembly Concept ID

- js/pages/questionnaire.js
Related: https://github.com/episphere/connect/issues/980
The dynamic import (ConnectApp -> questionnaire.js -> loadQuestConfig()) is preferred because it's up-to-date with Quest and Questionnaire updates, which are often updated off-cycle from our other apps. However, a fallback -> Implement questConfig fallback is needed when the dynamic import fails.
This PR implements a fallback config in the `loadQuestConfig()` catch block.
> implement questConfig fallback in loadQuestConfig catch block

- css/style.css
- js/pages/questionnaire.js
Related: https://github.com/episphere/connect/issues/1013
Fine-tuning the Quest container for screen readers (accessibility): 
• Update progress bar accessibility handling -> read percentage but skip reading enclosing container (navigation enhancement).
• Reduce whitespace around surveys for easier viewing & navigation -> especially in mobile view.
> quest container improvements

- js/pages/samples.js
Problem: Named export used for `fieldToConceptIdMapping.js` instead of default export.
Code Change:
- remove curly braces to export as default export
> BSWH Samples Page Not Displaying

- index.html
Related: https://github.com/episphere/connect/issues/945
Update Firestore Dependencies:
Firebase has resolved the IDBDatabaseError since the previous dependencies. The 'compat' versions I added are backward compatible.
We'll test these alongside Spanish integration testing.
> update ConnectApp Firestore Dependencies

- forms/consent/BSWH_Consent_V0.02.html
This PR is related to the issue:
- https://github.com/episphere/connect/issues/885
issue comment:
- https://github.com/episphere/connect/issues/885#issuecomment-2129925138 (4 & 5)
- https://github.com/episphere/connect/issues/885#issuecomment-2142669553
- Add to areas of BSWH HTML consent form, "space/blank line between phone number and consent document to separate these out some" and "between date and signature"
Code changes
- Add spacing using `<br>` element
> BSWH add spacing to html consent form

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/pages/questionnaire.js
- js/shared.js
* https://github.com/episphere/connect/issues/915
-----
* Now that Spanish has been added as a language to the PWA we need to render the correct markdown file depending on which language the participant is using. If a participant starts a survey in one language, they must finish the survey in that language.
-----
* added constant to `fieldToConceptIdmapping.js`
* added function `getMarkdownPath()` to `questionnaire.js`
* if a survey hasn't been started, use the language currently being used on the PWA
* if a survey has already been started, use the language the survey was previously started in
* added parameter `filter` to function `getMySurveys()`
* used to filter CID fields we want to be able to read in the PWA but won't have a corresponding …
> Reference Language-Specific Markdown

- js/shared.js
* N/A
-----
* use of keyword `assert` when importing JSON files in code is not supported anymore in some browsers
-----
* replacing `assert` keyword with `with`
> `assert` Bug Fix

- i18n/en.js
- i18n/es.js
- js/shared.js
* N/A
-----
* Firefox doesn't support assertions when importing files so the code was breaking when trying to import the local JSON files for i18n logic. The best solution I found to keep the process of accessing these files synchronous was to convert the JSON files to JS then export the object from the file.
-----
* Renamed `es.json` and `en.json` to `es.js` and `en.js`
* Updated references to files
> Browser Import Bug

- app.js
- js/pages/consent.js
- js/pages/myToDoList.js
- js/pages/settings.js
- js/settingsHelpers.js
* N/A
-----
* Spanish release has been pushed out a month, need to temporarily disable some code to minimize impact to PWA without having to revert all commits
-----
* `app.js`
* always setting language in `app state` to English
* disabling initialization of `languageSelectorContainer` and calls to `addEventLanguageSelector()`
* `consent.js`
* disabling updating participant document with `preferredLanguage` selection
* `myToDoList.js`
* disabling message suggesting option to switch survey languages
* `settings.js`
* removing initialization and references to all variables relating to preferred language
* `settingsHelpers.js`
* removed references to preferred language in `changeContactInformation()`
> Temporarily Disable Spanish

- js/pages/questionnaire.js
update Quest error handling fallback to most recent version v1.1.6
Quest releases: https://github.com/episphere/quest/releases
> update quest fallback version

- js/pages/questionnaire.js
- js/pages/ssn.js
- js/shared.js
* https://github.com/episphere/connect/issues/917
-----
* Module 1 needs to return SOCcer results in the correct language for WORK3 / WORK7 questions
-----
* Added `language` parameter when passing in `externalListeners()` to Quest
* Updated index of `target` we are grabbing value from since elements are wrapped with `fieldset` now
* `buildSoccerResults()` now calls external GCP Cloud Function to handle getting SOCcer results given title, task, and language
* Updated `updateStartSurveyParticipantData()` to call `getSelectedLanguage()` instead of accessing `appState` directly
> Soccer Updates

- js/pages/myToDoList.js
This PR address issue https://github.com/episphere/connect/issues/1017
ChangeLog
- Updated the condition for making sure the survey will become available on dashboard 120 hours (5 days) after completion of bio survey if participant is menstrual survey eligible
> [#1017] Change the condition to display Menstrual Survey

- js/pages/questionnaire.js
- js/shared.js
Related: Quest 2.0 improvements
https://github.com/episphere/connect/issues/1066
• Fetch survey data (questionnaire repo) from GitHub API with an authenticated request.
This should be more robust than using the raw file fetch and should eliminate response code 0 errors.
Note: Merge with Connect Faas PR: https://github.com/episphere/connectFaas/pull/623
> fetch survey modules through GitHub API (authenticated)

- js/pages/questionnaire.js
* N/A
-----
* Quest Tree is persisting in survey Firestore document after "resetting" of Menstrual Cycle Survey due to race conditions of storing the tree from Quest after nullifying fields from PWA
* If someone is starting a survey, we shouldn't even be trying to find a tree to pass into Quest
-----
* Created function `getTree()` for fetching `treeJSON` object from module document
* Only calling function for scenarios where a survey has been started already
> MCS Bug Fix

- js/shared.js
* https://github.com/episphere/connect/issues/759
-----
* Quest shouldn't be trying to reload the form when we submit, it should be handled by whatever is calling Quest if that functionality is needed.
* Re-Implementation of https://github.com/episphere/connectApp/pull/654
-----
* added `location.reload()` call at the end of `completeSurvey()` function
> Quest Reload

- js/pages/myToDoList.js
Update survey button handling for aria-label property (values read by screen reader).
Format (in en or es):
"Continue" or "Start" +  <Module Name>.
> update aria-label screen reader handling for survey buttons

- app.js
- i18n/en.js
- i18n/es.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
Updates in this PR:
- Add cancer screening history survey ([issue #1145](https://github.com/episphere/connect/issues/1145))
- Fix delayed app version refreshing ([issue #1171](https://github.com/episphere/connect/issues/1171))
- Automatically load Firebase configs for local development
- Removed un-used functions: addEventHideNotification, connectPushNotification, animateNotificationBell, manageNotificationTokens, getConceptVariableName
- Other minor cleanups
> Cancer screening history and other updates

- js/pages/settings.js
- js/shared.js
Small fixes found in testing:
•Null handle 250235523. This will be active in a future release, but is currently null for all stage and prod participants.
•rm leftover console.logs from inactivity timer testing.
> null handle 250235523, rm console.logs

- index.html
Update the Popper version for Quest Popovers (Bootstrap 5 compatibility)
> Update Popper Version

- js/pages/reports.js
Updates to handle viewing after declining and declining multiple times.  The timestamp should represent the first time the event happened and not updated after it is recorded.
> ROI Physical Activity Timestamp Updates

- i18n/en.js
The issue is a follow up to [issue#1269](https://github.com/episphere/connect/issues/1269)
Change:
Add an extra line break between address and directions text
> issue#1269 my samples edit 4

- js/components/navbar.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/agreements.js
- js/pages/consent.js
- js/pages/homePage.js
- js/pages/myToDoList.js
- js/pages/settings.js
- js/pages/support.js
For Issue: https://github.com/episphere/connect/issues/1334
Several places I updated the hard coded values for references to the field mapping to make the logic more readable
For the issue there are two main logic changes:
1) In myToDoList.js the logic to check and see if the passive participant is verified has been moved down from before the check for dataDestruction and consentWithdrawn to after.
2) In settings.js the logic to display the verification message also checks to see if the participant has withdrawn consent to mirror the logic for the editability of the page
> Updated Verification Message to be subordinate to Data Destruction and Consent Withdrawn

- app.js
- index.html
Per the feedback the app will collapse the header into a menu on small screens when the user is not logged in to keep it from causing the language selector to be cut off
> Collapse the header on small screens

- i18n/en.js
- i18n/es.js
- js/event.js
- js/pages/dashboard.js
- js/pages/healthCareProvider.js
- js/shared.js
For Issue 1423: https://github.com/episphere/connect/issues/1423
If the validatePin returns a not enrolling code then the participant is redirected to a message and can not proceed
If the user selects a non enrolling provider they will be presented with a message modal and can not proceed
If the user has already selected a provider but has not consented or finished the profile they will be presented with a warning message and will not be able to proceed
> Block Participants from Non Enrolling Sites
