NCI-C4CP/connectApp

- js/pages/myData.js
- js/pages/myToDoList.js
- js/pages/questionnaire.js
- js/shared.js
added logic between modules and competion TS. questionnaireModules URL will be updated when IMS is ready
> added logic between modules and competion TS

- js/pages/homePage.js
> Issue#276 add sign in page language

- js/pages/homePage.js
> additional language updates

- js/pages/consent.js
* changed date format of consent submit from yyyyddmm to yyyymmdd
> modified date format on consent submit

- js/shared.js
adding KPCO to site prod list
requesting reviews to make sure nothing else is needed to make this work
> added KPCO to prod site list

- index.html
- js/event.js
- js/shared.js
> Fixed page flash when confirming email in Firefox

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
* added biospecimen survey to questionnaire logic
> Issue#292 biospecimen survey

- app.js
@bhaumik55231 thoughts?
we are already calling getMyData() again later on line 277, so any potential updates that get pushed should already get pulled in.
> adding call to verify default concepts exist

- app.js
- js/shared.js
* added ability to check for baseline NORC payment eligibility
* needed to reference function from SM Dashboard repo
* calling new API endpoint in Faas
> Check payment eligibility

- app.js
- js/shared.js
* PR is for Issue #335 to set a derived variable based on the status of other baseline surveys
* adding function that can be built upon in the future
* intention of the function is to pull the participants data and check the conditionality of various derived variables
* if conditions are met, we can add an item to formData before it is pushed to the backend by storeResponse()
> Issue#335 all baseline surveys

- app.js
- js/components/navbar.js
- js/event.js
- js/pages/agreements.js
- js/pages/notifications.js
- js/pages/settings.js
* conditionally setting navigation bar based on if user profile is submitted and user has consented
* resulting bug fix inside of events.js
* bug fix in settings.js()
* updated messages in agreements, settings, and notifications.js()
> Issue#309 tab updates

- js/pages/myToDoList.js
* moved part of the module attribute initialization to it's own function
* created function to display notification when a new survey is available
> added logic for setting header

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/pages/questionnaire.js
- js/shared.js
* added Menstrual Cycle module information to field mappings document
* modified how surveys are unshifted onto display system array
* moved logic for enabling biospecimen and menstrual cycle modules
* added logic listeners for the answer to menstrual cycle survey
* added function tor remove menstrual cycle data if "no"
* added url to menstrual cycle survey
> Issue#333 menstrual cycle survey

- js/pages/footer.js
Adding Vulnerability Disclosure link to PWA footer
> adding Vulnerability Disclosure

- app.js
- js/event.js
- js/pages/healthCareProvider.js
- js/pages/myToDoList.js
* Toggling Pin Submit button based on PIN text input
* Setting CID 828729648 if "No PIN" is clicked
* Resolves https://github.com/episphere/connectApp/issues/352
> toggling button enable & setting CID

- js/pages/settings.js
* Removing Change Password functionality from My Profile tab
* Resolves https://github.com/episphere/connectApp/issues/346
> removing change password funcitonality

- js/pages/settings.js
* Updating text value showing email address after login email is updated
* Resolves https://github.com/episphere/connectApp/issues/348
> updating email

- app.js
- js/shared.js
* moved shared SM Dashboard function inside shared.js
* checkDefaults now inside Faas
> Cross repo fix

- index.html
- js/event.js
* content updates to Environment Warning Modal including link to prod site as well as access code box
* specific text phrase required to enable button that closes modal
> putting password lock on warning modal

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
Reverts episphere/connectApp#396
> Revert "testing"

- js/pages/consent.js
- js/shared.js
This PR addresses following issue:
https://github.com/episphere/dashboard/issues/402
Related PR:
https://github.com/episphere/dashboard/pull/410
> SiteManager Dashboard: Included consent F+L name in search query

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
[issue#350](https://github.com/episphere/connectApp/issues/350)
This PR addresses the following:
- added logic to display yellow bar "Thank you message" when user completes a standalone survey
- Introduce new concept Id 677381583- "Completed Standalone Surveys"
> Display  thank you message for submitting standalone survey 

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
[Isssue#350](https://github.com/episphere/connectApp/issues/350)
This PR addresses the following:
- fixed bug where "thank you for completing survey" message appears for users who completed a standalone survey but did not have the concept Id  [677381583](https://episphere.github.io/conceptGithubActions/web/#677381583) in their data object
- Removed standalone survey flags from questionnaire modules function and moved them to fieldToConceptIdMapping file
> Fix standalone thank you message logic

- js/components/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
* save known completed standalone surveys if concept does not exist
* set logic for users without the standalone concept Id and have completed standalone survey bug
* change suggestions from review, remove storeCompletedStandaloneSurveys
> dev to stage merge - Fix standalone thank you message logic (#403)

- js/pages/myToDoList.js
[issue#350](https://github.com/episphere/connectApp/issues/350) related
This PR addressed the following:
- changed wording for Thank you message
> Issue#350a standalone survey message wording change

- js/pages/myToDoList.js
This PR addresses the following changes from dev that will be merged to stage:
[Issue#350a standalone survey message wording change](https://github.com/episphere/connectApp/commit/696f490fac0a7d6f135452a3964d2abf2c25bf67)
[Menstrual Cycle header updates](https://github.com/episphere/connectApp/commit/b71b16c1e1551f0f19f7308873b9cec8e1534dc9)
> Merge from dev to stage 8-19-2022

- css/style.css
- js/pages/healthCareProvider.js
This PR resolve issue #122. The followings are details:
- Added "Required" to explain the red asterisk
- Added hover text to explain the red asterisk
> Issue#122 fix

- js/event.js
- js/shared.js
This PR resolves issue #377. The followings are details:
- Added concept ID 117249500, with value as the age of participant when submitting user profile information
- Updated getAge()
> Issue#377 fix

- app.js
- js/event.js
- js/pages/myToDoList.js
- js/shared.js
enabling clinical biospecimen survey based on My Collections
> Clinical enable

- index.html
This PR upgrades Firebase from version 7 to version 9 (compat version). It's a part of a bigger task aiming to solve issue #410.
The compat version is temporary, allowing old codes to run.  Code refactoring is needed to fully adapt Firebase modular version 9.
> upgrade to Firebase version 9 compat

- app.js
- js/pages/myToDoList.js
This PR is part of work solving issue #410. 
This PR updates `user.metadata.a` to `user.metadata.createdAt` for Firebase version 9
> Firebase upgrade fix

- app.js
- js/pages/myToDoList.js
Reverts episphere/connectApp#421
> Revert "Firebase upgrade fix"

- app.js
- css/style.css
- js/pages/homePage.js
This PR is follows PR #437, to fix magic link redirect issue.
> sign-in and sign-up

- js/components/form.js
- js/event.js
- js/pages/agreements.js
- js/pages/consent.js
- js/pages/settings.js
Files Affected (with changes):
form.js (User Profile Data Entry)
- removed functions not being called anywhere
- removed code that had been commented out
- removed imports that weren't being used
event.js
- removed imports that weren't being used
agreements.js (Forms)
- removed code that had been commented out
- removed event listeners for HTML objects that didn't exist
- removed export from functions only being called locally
- created function to return reused HTML structure
- updated parameters for calls to initializeCanvas()
- passing appropriate values for 883668444 and 577794331
- removing function parameters that weren't being called
consent.js (Initial Consent Loop)
- removed export from functions only being called locally
- removed code that had been commented out
- removed …
> Fixing Data Destruction / HIPAA Revocation

- app.js
- js/pages/homePage.js
This PR adds following improvements:
- Let user log in (without re-entering email) after magic link is clicked, if the same browser is used to request and open the magic link in the ( 1 hour ) time window
- Function getMyDate() is only called after user login (to resolve API call error in homepage)
> Magic link click

- js/pages/samples.js
These are updates for the henery_ford samples page. 
Added in a small if statement in the locations function to change the name of the title for henry_ford
> henry ford text update

- app.js
- index.html
This PR is to address issue https://github.com/episphere/connect/issues/613
* Adding Datadog RUM to frontend code
* Config used is based on tier code is running in
> Adding Datadog RUM

- app.js
This PR removes RUM during local development. It updates PR [#474](https://github.com/episphere/connectApp/pull/474), to resolve issue [#613](https://github.com/episphere/connect/issues/613).
> No RUM  in local development

- app.js
This PR is tied to issue https://github.com/episphere/connect/issues/613
* We are still in a trial period with Datadog and code needs to be moved to production
* To avoid cherry-picking code, commenting out code and adding conditionality so Datadog script isn't triggered in production
> Temporarily disabling Datadog in production

- app.js
- js/pages/homePage.js
- js/shared.js
This PR is to resolve issue [#617](<https://github.com/episphere/connect/issues/617>). Below are details:
- Set up tokenized sign in as normal sign in.
- Moved sign-in/sign-up entry logic from toggleNavBar() to homePage(), to eliminate a subtle race condition bug during sign-in/sign-up UI rendering.
- Cleaned up and beautified code.
> Sign in with a token

- js/pages/settings.js
Git hub Issue: https://github.com/episphere/connectApp/issues/349
Under the Sign In Information, it now displays the phone number or email used while logging in.
> made changes to display the phone number under SignIn Information

- js/pages/samples.js
Made changes in the mySamples page.
GitHub Issue Link: https://github.com/episphere/connectApp/issues/483
> made changes to the mySamples page of HenyFord

- .gitignore
- app.js
This PR is to fix issue [#497](https://github.com/episphere/connectApp/issues/497), and ensures  CID 335767902 exists after logging in with a token.
> Ensure CID 335767902 exists

- js/pages/homePage.js
Inserted text under the space provided to enter an email address : Update Text on Account Creation Page #469 
Issue Link: https://github.com/episphere/connectApp/issues/469
(https://user-images.githubusercontent.com/74061787/217064500-c5f409db-8a67-437d-ba83-902d662f180f.png)
> new text added under the email tab

- forms/HIPAA/HP_HIPAA_V1.0.html
- forms/consent/HP_Consent_V1.0.html
- forms/consent/NCI_Consent_V1.0.html
made changes to the PI in HP and NCI consent and HIPAA forms. 
Git hub issue link : https://github.com/episphere/connectApp/issues/491
> latest change added to  the PI for NCI_PI & HP

- forms/HIPAA/HP_HIPAA_V1.0.html
- forms/consent/HP_Consent_V1.0.html
- forms/consent/NCI_Consent_V1.0.html
Reverts episphere/connectApp#501
> Revert "latest change added to  the PI for NCI_PI & HP"

- js/pages/questionnaire.js
This PR is an update to https://github.com/episphere/connectApp/pull/495
* Updating regex to be more strict about what we allow for version numbers
> Module Versioning Update

- js/fieldToConceptIdMapping.js
- js/pages/agreements.js
Title^^
This PR addresses following issue: #491 
HFHS HIPAA FORM V1.0
[signed_hipaa-8.pdf](https://github.com/episphere/connectApp/files/11348131/signed_hipaa-8.pdf)
HFHS HIPAA FORM V0.02
[signed_hipaa-6.pdf](https://github.com/episphere/connectApp/files/11348137/signed_hipaa-6.pdf)
Sanford Consent FORM V0.02
[signed_consent-19.pdf](https://github.com/episphere/connectApp/files/11348150/signed_consent-19.pdf)
> HIPAA & Consent v0.02 forms: Fxed signatures alignment in Sanford Consent & HFHS Hipaa

- js/pages/questionnaire.js
This PR is an update to PR https://github.com/episphere/connectApp/pull/516
* Moved point of code where we set Start Time and Module Status to be not until SHA Code and Version match have been confirmed
* Updated regex to include two digits for major release number
* Logging errors to console for future debugging
* Scrolling window to top of screen after starting a module
> Module Versioning - Bug Fix

- js/pages/agreements.js
- js/pages/consent.js
This PR is to resolve issue [#520](https://github.com/episphere/connectApp/issues/520). Below are details:
- Use 'touchend' to trigger an additional click
- Not able to test on iPhone/iPad locally
> Fix double-tap issue

- js/pages/questionnaire.js
Rolling back version of Octokit used to v2.0.14 (temporarily)
> Octokit Hot Fix

- js/pages/questionnaire.js
- js/shared.js
> Prod -> Stage Sync 051823

- js/fieldToConceptIdMapping.js
- js/pages/settings.js
- js/settingsHelpers.js
ConnectApp - update to [#635](https://github.com/episphere/connect/issues/635) - user profile versioning
This PR brings connectApp user edit and profile archiving in sync with those features in SMDB.
• Add `changeRequestedBy` conceptId 611005658 (new requirement). This writes to each new map in the the user’s profile archive array (cId 569157507) when a profile edit is made for a verified participant.
• Add `additionalEmail2` field for compatibility with editable fields in SMDB.
• Update logic around verified participants.
At first, I thought the `verifiedFlag` conceptId was binary like the `profileSubmittedFlag`. I then found it can take multiple values, and the verified flag must correspond to the verified status, not just equal to cId.yes. This update resolves the mismatch problem.
• …
> Issue 635 add who requested change connect app

- app.js
Use Datadog in production ([#648](https://github.com/episphere/connect/issues/648))
> Use Datadog in prod

- js/pages/samples.js
The following Pull request (PR) addresses: https://github.com/episphere/connectApp/issues/548
Updates to the code:
1. Made changes to Locations and the timings.
2. Made a few edits under the heading How do I donate my samples?
> Made changes in the MySamples Page for Marshfield_Issue

- js/pages/myToDoList.js
This addresses [Deanna's comment](https://github.com/episphere/connectApp/issues/558#issuecomment-1591312891)
> [#558] Change title and description of covid-19 survey

- app.js
- js/shared.js
This is tied to PR https://github.com/episphere/connect/issues/638
When a new user signs in, they don't have data. Recently added logic caused the main page not to load for a new user.
> New User Bug Fix

- js/event.js
This PR fix a reference error (un-imported `appState`). It's part of dev->stage sync ([#577](https://github.com/episphere/connectApp/pull/577)).
> Add back appState import

- js/event.js
- js/shared.js
Issues Addressed
* Fixed bug where COVID-19 Survey was showing up on participant dashboards prematurely
> Dev -> Stage Sync 062623

- app.js
- js/pages/settings.js
- js/settingsHelpers.js
- js/shared.js
This PR updates https://github.com/episphere/connectApp/pull/564 for a bug fix and UX improvements suggested by the ops team
Bug fix:
We found a case where email authentication by magic link was deleting the participant's phone auth method. This fixes that issue by checking for consistency in auth methods (vs firestore participant profile) on connectApp login.
UX updates:
-added note about receiving a verification text when participant adds phone number
-updated handling of in-form values and buttons after an authentication update is completed
> Bug fix missing auth phone

- js/pages/samples.js
This PR addresses Issues https://github.com/episphere/connectApp/issues/548
* Removed list item from Preparation tab
* Updated format and text for location hours
> MF My Samples Fix

- js/pages/myToDoList.js
- js/pages/samples.js
* https://github.com/episphere/connectApp/issues/548
* https://github.com/episphere/connectApp/issues/558
Minor details needed to be updated including estimates for completion time for a few surveys as well as hours of availability for multiple Marshfield locations.
> Last Minute Updates

- js/pages/myToDoList.js
Changed text in duplicate account message, based on issue [#582](https://github.com/episphere/connectApp/issues/582).
> Changed text in duplicate account message

- js/pages/consent.js
Updates as specified in issue 596
> Updates for the consent final signing screen

- js/pages/samples.js
The following Pull request (PR) addresses: https://github.com/episphere/connectApp/issues/572
Link to the document : https://nih.box.com/s/pdbc23obuwpckgy9wt8kda2bl8h03q2d
Updates to the code:
Added a new location in the HFH My Sample page.
Made a few edits in hours under Henry Ford Medical Center - Livonia location.
> Added a new location and made changes in the timings.

- app.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/healthCareProvider.js
This PR implements frontend code for issue [#659](https://github.com/episphere/connect/issues/659).
> Implement duplicate account label check.

- js/pages/myToDoList.js
This PR addresses the issue https://github.com/episphere/connectApp/issues/563#issuecomment-1640419504
- Updated description of modules['Biospecimen Survey'] and modules['Clinical Biospecimen Survey'] in myToDoList.js`
> #[563] Edit the descriptions of some surveys

- js/pages/healthCareProvider.js
This PR updates text of duplicate account reminder ([#659](https://github.com/episphere/connect/issues/659)), to match text requested in issue [#582](https://github.com/episphere/connectApp/issues/582).
> Update text of duplicate account reminder

- js/event.js
- js/pages/healthCareProvider.js
Syncing changes from dev to stage.
•[Make preferred name searchable on signup](https://github.com/episphere/connect/issues/678)
> Dev -> Stage Sync (make prefName searchable on signup)

- js/pages/agreements.js
this PR addresses some comments from PR https://github.com/episphere/connectApp/issues/537
- Updated participant signature to address comment https://github.com/episphere/connectApp/issues/537#issuecomment-1666025860
- Added the suffix to participant signature to address comment https://github.com/episphere/connectApp/issues/537#issuecomment-1666137280
> [#537] Update participant signature

- js/pages/samples.js
The issue address is : https://github.com/episphere/connect/issues/688#issue-1835562887
**The changes made in the code are:**
Removed the hours
Added new information under What Happens subheading.
**Latest document for reference:**
[Sanford_My Samples page_08032023_tracked-2.docx](https://github.com/episphere/connectApp/files/12401141/Sanford_My.Samples.page_08032023_tracked-2.docx)
> added new changes in MySamples

- js/pages/samples.js
Adresses updates for https://github.com/episphere/connect/issues/686
> Henry Ford Location Updates Aug

- app.js
- css/style.css
- js/pages/homePage.js
- js/pages/settings.js
For issue: https://github.com/episphere/connect/issues/682
> Multiple login updates

- js/pages/settings.js
- js/settingsHelpers.js
Updated per comments provided in https://github.com/episphere/connect/issues/682
> Updated error messages for invalid phone pin and update timeout

- js/pages/settings.js
This PR addresses:
Profile not complete div stacking: https://github.com/episphere/connect/issues/699
Undefined 699625233 intermittent DataDog error: https://github.com/episphere/connect/issues/698
•Reset template at the beginning of renderSettingsPage() to clear for each new render.
•Check userData for truthiness in the buildPageTemplate conditional.
> fix div stacking & datadog undefined 699625233 err

- js/pages/homePage.js
Worked on all the links which were showing errors in the code and replaced the new Privacy act link with the new link. 
This PR addresses the issue: https://github.com/episphere/connect/issues/727
> worked on the hyperlinks and updated the new privacy link

- css/style.css
Made final changes in the dimensions of the images as suggested by Deanna.
This PR addresses the issue: https://github.com/episphere/connect/issues/727
> made changes in the dimensions.

- css/style.css
This PR is regarding the issue: https://github.com/episphere/connect/issues/727
1. Added content alignment.
2. Made changes in dimensions after checking in mobile phone.
> Connect mobile issue 727

- css/style.css
This issue addresses : https://github.com/episphere/connect/issues/727
Resized the images to look aligned in all mobile screens.
> resizing the content

- css/style.css
Issues Addressed:
* https://github.com/episphere/connect/issues/702 (@anthonypetersen)
> Dev -> Stage Sync (Sep. Release Late Add)

- index.html
* https://github.com/episphere/connect/issues/760
-----
* Now that we are using DataDog we no longer need to have a script for initializing Sentry
-----
* removed `<script>` block
> Remove Sentry Initialization 

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
* https://github.com/episphere/connect/issues/737
-----
* Adding new survey for At-Home Mouthwash collection
-----
* added necessary constants in `shared.js`
> Add Mouthwash Survey

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
* https://github.com/episphere/connect/issues/737
-----
* Disabling new survey for At-Home Mouthwash collection until November release
-----
* updated constant in `fieldToConceptIdMapping.js`
* updated survey descriptors
* removed statement to enable survey
> Disable Mouthwash Survey

- js/shared.js
* https://github.com/episphere/connect/issues/759
-----
* There are currently changes in Quest Dev that aren't tied to this that would negatively impact the PWA until further changes are made here. I will be removing this from dev and stage until it is ready.
-----
* commented out code
> Disabling Quest Change

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
This PR adds trigger for mouthwash collection survey, as described in issue [#737](https://github.com/episphere/connect/issues/737). Some code cleanup was also done.
> Add mouthwash survey trigger

- js/pages/homePage.js
- js/pages/settings.js
- js/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/709
> [#709] Reauth settings

- js/pages/questionnaire.js
* TBD
-----
* If a new Release was created in the Quest repo, changes were automatically seen across all branches of the PWA. We want to import Quest functionality from different sources depending on the URL being used in the PWA
-----
* Removed top-level imports of needed Quest functions
* Created function `importQuest` that takes in a file name and a function name
* Added calls to new function where needed
> Quest Dynamic Import

- js/pages/questionnaire.js
Bugs exist in other branches, pointing everything to the last release.
> Temporarily Setting URL for Quest

- js/pages/questionnaire.js
Pulling directly from release number
> Quest Hardcode

- js/pages/questionnaire.js
Hardcoding Quest version that gets imported
> Dev -> Stage (Late Updates)

- js/pages/questionnaire.js
Needed to apply updates to Quest import version prior to November Release
> Quest Cherry Picking

- js/pages/myToDoList.js
This PR adjust home mouthwash survey trigger condition in PR [#665](https://github.com/episphere/connectApp/pull/665), based on specifications in issue [#737](https://github.com/episphere/connect/issues/737).
> Home mouthwash trigger

- css/style.css
- js/pages/consent.js
- js/pages/notifications.js
**This Issue refers to the issue:**  https://github.com/episphere/connect/issues/722
**Document for reference:**  https://nih.box.com/s/9fw5zwb5i8n90qg0afx5nuu914bk31mk
**The changes made in this PR are:**
1. Made changes in the survey icon under the Messages tab.
2. Increased the padding for the next button.
3. Added the hover effect to the Previous button. 
**I am attaching the screenshot before changes for reference:**
**I am attaching the screenshots after changes for reference:**
> Design and style fixes in PWA

- js/pages/questionnaire.js
Reverts episphere/connectApp#690
> Revert "Revert "Enabling Dynamic Quest Versions""

- dev/config.js
- js/pages/questionnaire.js
- prod/config.js
- stage/config.js
* https://github.com/episphere/connect/issues/858
-----
* Additional questions have been added to Module 1 ( `WORK3B` and `WORK7B`). The responses in these questions need to be combined with the responses from questions `WORK3` and `WORK7` when fetching information from SOCcer.
-----
* made `data` and `modules` global variables to be used across functions in `questionnaire.js`
* modified dev, stage, and prod Soccer URLs in `config` folders
* updated `soccerFunction()` to `externalListeners()`
* added `buildSoccerResults()` to handle calling Soccer
* added constants and event listeners for `WORK3B` and `WORK7B`
* cleaned up code
> Module 1 Soccer Updates

- css/style.css
- index.html
- js/pages/myToDoList.js
- js/pages/ssn.js
- js/shared.js
* https://github.com/episphere/connect/issues/712
-----
* The SSN Survey is being moved outside of Quest and into an on-screen Frame within the To-Do List of the PWA. This PR addresses the front-end changes needed.
-----
* Added new classes to `style.css`
* Added new HTML modal to `index.html`
* Added logic to `myToDoList.js` to handle SSN Start button differently from other modules
* Cleaned up ESLinst errors in `myToDoList.js`
* Remove SSN Module path from `shared.js`
* Added `storeSocial()` function to call new API end-point
* Added file `ssn.js` to handle workflow of module
**NOTE: Should be moved along tiers with [API PR](https://github.com/episphere/connectFaas/pull/499)**
> SSN Survey Functionality Updates

- css/style.css
- js/pages/myToDoList.js
- js/pages/questionnaire.js
- js/pages/ssn.js
This PR addresses a feedback from the following Pull Request:
* https://github.com/episphere/connectApp/pull/698
-----
* Feedback was given by the operations team on how they would like the questionnaire to look and feel.
-----
* Added classes to `style.css`
* Reverted previous changes to `myToDoList.js`
* Capitalized "Number" in `myToDoList.js`
* Modified logic in `questionnaire.js` so questionnaires that don't use Quest can utilize much of the same code
* Updated and renamed function in `questionnaire.js` so that questionnaires could be rendered with or without status bar
* Added documentation to `ssn.js`
* Added ability to toggle viewing SSN entries in `ssn.js`
* Added support for auto-generated hyphens in `ssn.js`
* Checks for valid SSN are now checked when you leave the text box …
> PR 698 - Feedback Updates

- js/pages/ssn.js
This PR addresses a feedback from the following Pull Request:
* https://github.com/episphere/connectApp/pull/698
-----
* A second round of feedback was given by the operations team on how they would like the questionnaire to look and feel.
-----
* Bolded instances of `4 digits` in `ssn.js`
* Fixed bug allowing letters in four digits entries in `ssn.js`
* Added the work `Survey` to end buttons in `ssn.js`
> PR 698 - Feedback Updates V2

- js/pages/myToDoList.js
This PR addresses a feedback from the following Pull Request:
* https://github.com/episphere/connectApp/pull/703
-----
* Previous decision to move the COVID-19 Survey to the bottom of the To-Do List is causing the SSN Survey to not move to Completed after submission. Decision was made to throw COVID-19 at the top of the To-Do List when it's available, but position it so it's under higher priority surveys.
-----
* Removed logic from [this](https://github.com/episphere/connectApp/pull/595) Pull Request
* Adjusted the position the COVID-19 Survey is unshifted to the Display System array
> PR 698 - Feedback Updates V3

- js/pages/notifications.js
- js/shared.js
This PR implements fixes described in PR [#875](https://github.com/episphere/connect/issues/875), and also some cleanups.
> Fix display of notification messages

- js/shared.js
This PR is a minor update to the following Pull Request:
* https://github.com/episphere/connectApp/pull/708
-----
* New PROMIS QOL Survey is being added to the study and logic needs to be put in to display the survey at the right time on the To-Do List, render the appropriate Quest markdown, and send off survey responses to the API
-----
* Updated markdown file name in `shared.js`
> PROMIS Survey Updates (PWA)

- js/pages/agreements.js
For Issue https://github.com/episphere/connect/issues/879
and for the age expansion project https://github.com/episphere/connect/issues/868
> Pdf signature Updates

- js/pages/agreements.js
Some minor updates to the consent coordinates
> Updated PDF Coordinates

- forms/consent/HFHS_Consent_V0.03.html
- forms/consent/HP_Consent_V0.04.html
- forms/consent/KPCO_Consent_V0.03.html
- forms/consent/KPGA_Consent_V0.03.html
- forms/consent/KPHI_Consent_V0.03.html
- forms/consent/KPNW_Consent_V0.03.html
- forms/consent/Marshfield_Consent_V0.03.html
- forms/consent/NCI_Consent_V0.05.html
- forms/consent/Sanford_Consent_V0.03.html
- forms/consent/UChicago_Consent_V0.05.html
- js/pages/homePage.js
This PR follows [PR#711](https://github.com/episphere/connectApp/pull/711), and is based on feedback. Below are details:
- Add microscope icon to each html consent form
- Fix mixed email and Connect support links in each html consent form
- Fix broken tables in NCI and KPGA html consent forms
- Minor text updates
> Fix icon and other issues

- js/pages/homePage.js
This PR follows [PR#711](https://github.com/episphere/connectApp/pull/711). Below are details:
- Remove spaces before periods, based on feedback.
> Remove spaces before periods

- js/pages/questionnaire.js
- js/shared.js
Related: https://github.com/episphere/connect/issues/909
Work towards survey loading issue resolution:
(1) Find survey sha value and version number based on commit history in GitHub API.
(2) Repair the survey file with sha and version data when sha is missing.
(3) Optimize/Parallelize the loading sequence where possible.
(3) Additional error handling to diagnose remaining issues.
> Update survey handling on survey continuation

- js/pages/questionnaire.js
* N/A
-----
* Prior code feature is missing two parameters when calling the `getModuleSHA()` function
-----
* Added parameters `Connect ID` and `Module ID` to function call
> Added Missing Parameters

- js/pages/homePage.js
- js/pages/signIn.js
- js/shared.js
This PR:
- Implements [issue #907](https://github.com/episphere/connect/issues/907).
- Cleans up some code. Google sign-up in dev is removed, to be consistent with stage and prod tiers.
> Emphasize Phone sign-up

- app.js
- js/event.js
This is to help debug issue https://github.com/episphere/connect/issues/925
> Added logging for when we attempt to save an empty firstSignInTime

- js/shared.js
This PR:
- Implements requirement in [issue#932](https://github.com/episphere/connect/issues/932)
- Has some clean-ups
> Update text after sending out sign-in email

- js/shared.js
This PR follows [PR#730](https://github.com/episphere/connectApp/pull/730), to direct users to sign-in UI after clicking "Back" button, after sending out the sign-in email.
> Adjust sign-up flow

- js/pages/myToDoList.js
For issue https://github.com/episphere/connect/issues/992
> Language update for the home mouthwash

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
Hard coded Spanish survey links.
> Temporary hard coding of the spanish surveys

- js/pages/ssn.js
* https://github.com/episphere/connect/issues/964
-----
* Small text changes have been requested to increase clarity in SSN Module
-----
* Added a sentence as well as markdown to bold and underline a few phrases
> SSN Survey Text Changes

- js/pages/samples.js
This PR addresses issue https://github.com/episphere/connect/issues/982
ChangeLog
- Updated the content of UChicago sample.
> [#982] Update UChicago sample

- js/pages/samples.js
This PR addresses issue https://github.com/episphere/connect/issues/942
> [#942] Update content of samples page -Sanford

- js/pages/samples.js
This PR addesses issue https://github.com/episphere/connect/issues/942
ChangeLog
- Add break line as Deanna's request.
> [#942] Samples Page Sanford

- js/fieldToConceptIdMapping.js
- js/pages/questionnaire.js
Related: https://github.com/episphere/connect/issues/931
Updated: push SOCcer question topics inside the accessible `<fieldset>` (they were going into that div, the fieldset is new).
Cleanup: menstrual survey - accessibility - read the progress bar don't read the container.
> soccer accessibility

- js/pages/samples.js
This PR is related to the issue:
- https://github.com/episphere/connect/issues/885
issue comments:
- https://github.com/episphere/connect/issues/885#issuecomment-2141071122
- Text correction changes on Box (https://nih.app.box.com/file/1470374610468?s=6mb9dqsa9jp983ztm57dlhpdqp5esc4d)
Code Changes
- Moved custom data attribute `data-i18n` from div element to span element to address missing BSWH in heading
- Fixed text content (Reference box link above)
> Missing BSWH on header

- i18n/en.json
- i18n/es.json
- js/components/form.js
- js/event.js
- js/pages/agreements.js
- js/pages/consent.js
- js/pages/healthCareProvider.js
- js/pages/settings.js
- js/shared.js
Continuation of Spanish Bucket 2: https://github.com/episphere/connect/issues/915
> Translation

- i18n/en.js
- js/components/navbar.js
Language selector in navbar now labeled as "language" (per feedback on [915](https://github.com/episphere/connect/issues/915)).
> 915 requested updates

- i18n/es.js
The newest reply on [915](https://github.com/episphere/connect/issues/915#issuecomment-2159156080) requests the Spanish language label for the language selector be changed.
> Additional update as requested on 915

- js/pages/samples.js
This PR addresses comment https://github.com/episphere/connect/issues/885#issuecomment-2160981538
> [#885] Add the site name

- js/pages/questionnaire.js
update Quest fallback to v1.1.7
> update quest fallback version

- js/pages/questionnaire.js
update Quest fallback to v1.1.8
> version update

- js/pages/questionnaire.js
update Quest fallback - v1.1.9
> update quest fallback 1.1.9

- app.js
Related: https://github.com/episphere/connect/issues/1015
Add Connect ID to DataDog sessions for better error tracing & debugging.
-add to the existing session upon authentication.
-end session connection at logout.
> add Connect ID to DataDog

- js/pages/questionnaire.js
> Quest Fallback Version Update

- js/pages/questionnaire.js
- js/shared.js
Related: https://github.com/episphere/connect/issues/1048
-add `getAppSettings` function
-add Firestore `appSettings` collection
-update Quest version fetching process 
NOTE: Merge with ConnectFaas https://github.com/episphere/connectFaas/pull/612
> add getAppSettings and update questConfig loading method

- js/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/1057
> Spanish Translation: magic link emails for login 

- forms/HIPAA/HFHS_HIPAA_V0.02_Span.html
- forms/consent/BSWH_Consent_V0.02_Span.html
- forms/consent/HFHS_Consent_V0.03_Span.html
- forms/consent/HP_Consent_V0.05_Span.html
- forms/consent/Marshfield_Consent_V0.03_Span.html
- forms/consent/Sanford_Consent_V0.03_Span.html
Updates as requested from comment https://github.com/episphere/connect/issues/915#issuecomment-2236883003 and down
> Updates to the formatting and content of the consent/hippa forms

- i18n/en.js
- i18n/es.js
- js/pages/consent.js
- js/pages/healthCareProvider.js
Fixes the Heard About the Study checkboxes and the header when in a mobile form factor https://github.com/episphere/connect/issues/1071
> Fixes to the consent flow

- js/pages/homePage.js
This PR addresses issue https://github.com/episphere/connect/issues/1070
ChangeLog
- Update localStorage value after pressing enter key of email input.
> [#1070] Fix: Safari email magic link issues 

- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
this PR address the issue https://github.com/episphere/connect/issues/1006
> [#1006] PROMIS Rollout to Backlog

- app.js
If the old html is cached this will attempt to reload the window and get the new div.  If the new div is not loaded it will ignore rendering the selector.  The app will still work it just wont have the ability to change the language from English.
> Update missing container div

- js/pages/myToDoList.js
This PR addresses issue https://github.com/episphere/connect/issues/1103
> [#1003] Fix: Promis survey not showing in completed tab

- .gitignore
- app.js
Part of [1054](https://github.com/episphere/connect/issues/1054).
> Updated code to include localDevFirebaseConfig

- app.js
- i18n/en.js
- i18n/es.js
- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/shared.js
For Issue: https://github.com/episphere/connect/issues/1073
> 2024 Connect Experience Survey

- js/fieldToConceptIdMapping.js
> Updated 2024 experience survey to new module ID

- js/pages/myToDoList.js
Experience 2024 module now checks for existence of status flag vs. date range
> Experience2024 module eligibility check change

- i18n/en.js
- i18n/es.js
- js/pages/myToDoList.js
Per feedback on [1073](https://github.com/episphere/connect/issues/1073).
> Updated time estimate on 2024 Connect Experience Survey

- forms/formVersions.js
For issue: https://github.com/episphere/connect/issues/1132#issuecomment-2429976469
> KPCO Consent and HIPAA fix

- i18n/en.js
- i18n/es.js
Fix for the iframe and download links
> Fixed Iframe and download links

- js/pages/questionnaire.js
* https://github.com/episphere/connect/issues/1146
-----
* Removed `AGE` as a Quest variable
* Added `yob` as a Quest variable
> Quest Input Variables

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
This PR addresses issue https://github.com/episphere/connect/issues/994
> [#994] Part 1: User Profile Enhancements for Intro and MyProfile page 

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
- js/settingsHelpers.js
- js/shared.js
This PR addresses issue https://github.com/episphere/connect/issues/1149
NOTE:  The USPS API on import is not yet implemented.
> [#1149] User profile contact information

- js/pages/questionnaire.js
Update Quest 2.0 paths based on yesterday's implementation conversation.
> update Quest 2.0 paths

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
- js/pages/settings.js
- js/settingsHelpers.js
> Addresses various notes on user profile enhancements from testing

- i18n/es.js
Part of [994](https://github.com/episphere/connect/issues/994) notes.
> Added missing Spanish translations

- js/components/form.js
- js/event.js
This PR temporarily disable POBOX feature of issue https://github.com/episphere/connect/issues/1149 since it works improperly
> Disable POBox feature

- app.js
- js/shared.js
Related: https://github.com/episphere/connect/issues/1167
(related because updated Bootstrap5 modal handling made outstanding issues with modals and event listeners more visible)
Previous issue:
A timing issue in the auth routine caused these event listeners to miss connection in some cases. Then, with those listeners firing, we found a bug impacting windows/tabs in the background.
This PR:
Update inactivity timer due to a bug we found with magic link sign on:
Details:
Magic links open up a new browser tab when they’re clicked. If the original tab is in the background, and the timer is attached when onAuthStateChange is triggered, that timer can cause the user to be signed out when the user doesn’t return to that initial tab.
This update:
Access a shared timestamp and warning modal state …
> handle inactivityTimer with MyConnect open in multiple tabs or windows

- README.md
- js/pages/questionnaire.js
- js/settingsHelpers.js
- js/shared.js
Removing references to `episphere` after repository move to `NCI-C4CP`
> URL Updates

- js/shared.js
Related: https://github.com/episphere/connect/issues/1183
Fix missing `COMPLETED` value on Quest 1 survey submission.
> Hotfix quest1 complete survey bug

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
- js/pages/settings.js
- js/settingsHelpers.js
- js/shared.js
this pr addresses issue https://github.com/episphere/connect/issues/1178
> [#1178] User profile enhancements part 3

- serviceWorker.js
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/1
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/2
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/3
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/4
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/5
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/6
-----
* Updating regular expressions to match hostnames as intended
> Code Scan Fix (Regular Expressions)

- js/shared.js
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/11
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/12
-----
* Removed local storage of email addresses during sign-in
> Stage -> Prod Sync (Local Storage Fix)

- js/pages/notifications.js
* https://github.com/NCI-C4CP/connectApp/security/code-scanning/17
-----
* Added loop for removing `style` blocks from notification body
> Code Scan Fix (Notification Sanitization)

- js/pages/homePage.js
Dev -> Stage Cherry Pick: use div value for sign up email
> Dev -> Stage Cherry Pick: use div value for sign up email

- js/pages/homePage.js
I tested this in dev and stage.
Stage -> Prod Cherry Pick: Use div value for sign up email
> Stage -> Prod Cherry Pick: Use div value for sign up email

- js/event.js
https://github.com/episphere/connect/issues/1204
> added comments

- js/event.js
Ref: Revert code of removing space of email, this feature will be in the hotfix release (after Jan release)
>  Revert code of removing space of email

- js/event.js
- js/shared.js
Ref: https://github.com/episphere/connect/issues/1191
> [#1191] SendGrid email validation scoring affecting participants User Profile creation

- serviceWorker.js
Version Update for Hot Fix (https://github.com/NCI-C4CP/connectApp/pull/928)
> Service Worker

- js/shared.js
Fix alert from CodeQL scanning [here](https://github.com/NCI-C4CP/connectApp/security/code-scanning/23).
> Fix CodeQL alert

- js/event.js
- js/shared.js
Ref: https://github.com/episphere/connect/issues/1181
> [#1181] User Profile email address warning messages

- i18n/en.js
- i18n/es.js
- index.html
- js/components/form.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
- js/pages/settings.js
- js/settingsHelpers.js
- js/shared.js
Related:
https://github.com/episphere/connect/issues/1186
https://github.com/episphere/connect/issues/735
Add alt address and alt contact to sign up form and profile edit form.
Update modal handlers in sign up to prevent accidental double-click issues
remove 'System' from 'Henry Ford Health System'
> Add alt address and alt contact

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
- js/fieldToConceptIdMapping.js
- js/pages/settings.js
- js/settingsHelpers.js
Related: https://github.com/episphere/connect/issues/1186
Logic and translation refinements after testing
> 1186 - logic and translation refinements

- i18n/en.js
- i18n/es.js
- js/components/form.js
- js/event.js
- js/pages/agreements.js
- js/pages/consent.js
- js/pages/settings.js
- serviceWorker.js
Related: https://github.com/episphere/connect/issues/1186
• Casing updates for name field headers
• Spanish update
• Bold alt address text
> Casing and Spanish updates

- i18n/en.js
- i18n/es.js
- js/pages/settings.js
- js/settingsHelpers.js
Related: https://github.com/episphere/connect/issues/1190
update modal handling -> USPS address validation.
> Usps modal handling

- js/event.js
- js/pages/settings.js
- js/settingsHelpers.js
Ref: https://github.com/episphere/connect/issues/1181
> [#1181]  Interim modal for My Profile email address warning messages 

- js/event.js
Ref: https://github.com/episphere/connect/issues/1216
> Implement usps validation for alternate address

- js/shared.js
Update survey completion handling
•This will resolve a persistent but inconsequential error in DataDog that has occurres after successful survey completion (while the page reloads) and has been clogging our error reporting pipeline.
> quest submit survey updates

- js/event.js
> [Stage][Hotfix] Comment out sg email validation temporarily

- js/event.js
- serviceWorker.js
Ref: https://github.com/episphere/connect/issues/1256
> [Sync] Stage -> Master

- js/settingsHelpers.js
Ref: https://github.com/episphere/connect/issues/1247
> Disable SG validation in myProfile temporarily

- js/event.js
- serviceWorker.js
ISSUE: Participants are unable to submit user profiles and it is not entirely clear after troubleshooting what is preventing them.
This temporary solution will add clarity within our DataDog logs as to what is causing participants issues and hopefully help uncover the root bug sooner. This hot fix also fixes an false positive error from popping up in our logs when validating mail addresses.
> Temp Hotfix

- i18n/en.js
- i18n/es.js
- js/event.js
- js/settingsHelpers.js
Ref: https://github.com/episphere/connect/issues/1216
> Usps api invalid city handling

- i18n/en.js
- i18n/es.js
- js/event.js
- js/settingsHelpers.js
- serviceWorker.js
> Dev -> Stage

- i18n/en.js
- i18n/es.js
- js/pages/consent.js
For Issue: https://github.com/episphere/connect/issues/1195
> Update for name validations

- js/event.js
Ref: https://github.com/episphere/connect/issues/1215
> Fix issue of google places autocomplete

- i18n/en.js
- i18n/es.js
- js/pages/settings.js
- js/settingsHelpers.js
- js/shared.js
Ref: https://github.com/episphere/connect/issues/1207
> Implement clearing physical/alternate address

- js/event.js
This PR addresses comment https://github.com/episphere/connect/issues/1247#issuecomment-2786922763
> Handle address line 2 at verification screen

- js/event.js
- js/settingsHelpers.js
This PR addresses issue https://github.com/episphere/connect/issues/1181
> [#1181] Uncomment SG email validation code

- js/pages/settings.js
- js/settingsHelpers.js
Ref: https://github.com/episphere/connect/issues/1207
> Hide clear button if user is not verified

- i18n/en.js
- i18n/es.js
- js/fieldToConceptIdMapping.js
- js/pages/myToDoList.js
This adds a notification for when the user has completed all enabled surveys.  For Issue: https://github.com/episphere/connect/issues/1227
> New Completed Survey Message

- js/pages/myToDoList.js
For Issue: https://github.com/episphere/connect/issues/1227
> Fixed Completed Survey Logic

- js/pages/myToDoList.js
Small update per request in issue: https://github.com/episphere/connect/issues/1227
> Adjusted when the survey language not is diplayed

- js/pages/samples.js
This PR is a follow up to [issue#1269](https://github.com/episphere/connect/issues/1269) related to the following:
- https://github.com/episphere/connect/issues/1269#issuecomment-2821848903
Commented "Duchossois Center for Advanced Medicine (DCAM) Outpatient Labs" (See above comment link)
> Temporarily remove Duchossois Center for Advanced Medicine (DCAM) 

- js/pages/settings.js
Update message to Mailing Address Change Failed! when click clear button
> update error message in address

- js/settingsHelpers.js
- js/shared.js
Sendgrid mail validation https://github.com/episphere/connect/issues/1300
> sendgrid mail validation in alt contact

- js/settingsHelpers.js
Empty Physical/Alternate address fields should be changed to NULL https://github.com/episphere/connect/issues/1304
> change empty string to null

- app.js
- i18n/en.js
- i18n/es.js
- js/fieldToConceptIdMapping.js
- js/shared.js
Related: https://github.com/episphere/connect/issues/1238
• Add external survey variable (DHQ API)
• Update language on My To-Do list
> DHQ testing updates

- i18n/es.js
Related: https://github.com/episphere/connect/issues/1238
•Add final sentence to DHQ Spanish translation in My To-Do List.
> Final translation My ToDo List Spanish

- js/event.js
- js/pages/myToDoList.js
* https://github.com/episphere/connect/issues/1285
-----
* Logic for setting UTM variables needed to be moved so that participants with tokenized links still have variables stored
> UTM Logic Move

- i18n/en.js
- i18n/es.js
- js/pages/samples.js
This PR is a follow-up to [issue#1309](https://github.com/episphere/connect/issues/1309):
- https://github.com/episphere/connect/issues/1309#issuecomment-2917571520
Change request and code changes:
Remove comma and add a space to a Marshfield address
> Issue#1309 follow up 2

- js/pages/ssn.js
* https://github.com/episphere/connect/issues/1002
-----
* Missed one `if` block for adding a `return` statement
> SSN Flow - Bug Fix (Update)

- css/style.css
- js/pages/samples.js
- js/pages/settings.js
Style Updates per feedback on issue 1441: https://github.com/episphere/connect/issues/1441
> Style Updates

- js/pages/notifications.js
- js/shared.js
Updated so that only the call made from the notifications page sets the read flag for messages instead of every call to retrieveNotifications.  I also added a some code to make sure only one call to the api is called at a time to avoid race conditions.
I had code fix the spacing on shared.js so there are a lot of whitespace changes but the relavant code change is 1460 to 1490.
> Updated Message Notification to be more sticky

- js/components/navbar.js
- js/pages/settings.js
- js/settingsHelpers.js
Updated the navbar to remove the data destroy check and always allow access to the my profile page.
Updated the my profile page to better handle missing page components
> Update for Data Destroyed User on the settings page
